services:
  django:
    image: django-rest-app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend_django:/app  # Assurez-vous que le chemin est correct
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend_django.settings
      - CORS_ALLOW_ALL_ORIGINS=False
      - CORS_ORIGIN_WHITELIST=http://localhost:3001,http://127.0.0.1:3001,http://local.myopenedx.com,http://studio.local.myopenedx.com,http://127.0.0.1:7860
    networks:
      - webnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure  # Redémarre le conteneur si l'application échoue
        delay: 10s              # Attendre 10 secondes avant de redémarrer
        max_attempts: 3         # Nombre maximum de tentatives de redémarrage
        window: 30s             # Fenêtre de temps pour les tentatives de redémarrage

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - webnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    depends_on:
      - django
    networks:
      - webnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s

  react:
    image: react-app
    ports:
      - "3000:3000"
    networks:
      - webnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s

  langflow:
    image: langflow:latest
    ports:
      - "7860:7860"
    networks:
      - webnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s
   

networks:
  webnet:
    driver: overlay
    attachable: true  # Permet aux conteneurs de se connecter manuellement au réseau